#!/usr/bin/python3
"""
Module 1-my_list

A module that defines a class MyList that inherits from list.
"""


class MyList(list):
    """
    MyList class inherits from list and adds a print_sorted method.
    """

    def print_sorted(self):
        """
        Prints the list sorted in ascending order
        without modifying the original list.
        """
        print(sorted(self))
